repos:
- repo: https://github.com/alan-turing-institute/CleverCSV-pre-commit
  rev: v0.6.6
  hooks:
  - id: clevercsv-standardize
- repo: git@github.com:Yelp/detect-secrets
  rev: v1.0.3
  hooks:
  - id: detect-secrets
    args:
      - --exclude-files
      - go.sum