kind: Service
apiVersion: v1
metadata:
  name: adoption-api
  namespace: adoption
spec:
  selector:
    app: adoption-api
  type:  ClusterIP
  ports:
  - name:  http
    port:  3000
    targetPort:  3000